[package]
name = "robcos"
version = "0.3.2"
edition = "2021"
description = "RobCoOS â€” Fallout-style terminal OS in Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Stylith/RustCoOS"

[[bin]]
name = "robcos"
path = "src/main.rs"

[[bin]]
name = "robcos-native"
path = "src/bin/robcos_native.rs"

[dependencies]
ratatui       = "0.29"
crossterm     = { version = "0.28", features = ["event-stream"] }
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
anyhow        = "1"
sysinfo       = "0.32"
chrono        = { version = "0.4", features = ["clock"] }
rand          = "0.8"
sha2          = "0.10"
hex           = "0.4"
dirs          = "5"
portable-pty  = "0.8"
vt100         = "0.15"
eframe        = { version = "0.29", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
image         = { version = "0.25", default-features = false, features = ["png"] }

[build-dependencies]
winres        = "0.1"

[features]
default = []
sound   = []          # enable via: cargo build --features sound

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true
